import { getLogoDataUri } from "@/lib/logo-base64";

interface QuotePdfParams {
  quote: {
    version_number: number;
    quoted_price: number | null;
    currency: string | null;
    terms_text: string | null;
    exclusions_text: string | null;
    status: string | null;
    created_at: string;
  };
  projectName: string;
  clientName?: string;
  address?: string;
  estimateSummary?: {
    total_estimated_cost: number | null;
    version_number: number;
  };
}

export async function exportQuotePdf(params: QuotePdfParams): Promise<void> {
  const { quote, projectName, clientName, address, estimateSummary } = params;
  const logoDataUri = await getLogoDataUri().catch(() => "");
  const dateStr = new Date(quote.created_at).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const currency = quote.currency || "CAD";
  const fmtPrice = (p: number | null) => p != null ? `${currency} $${p.toLocaleString(undefined, { minimumFractionDigits: 2 })}` : "—";

  const html = `<!DOCTYPE html><html><head><title>Quote v${quote.version_number} — ${projectName}</title>
<style>
@page{margin:0.8in;size:letter}
*{box-sizing:border-box}
body{font-family:'Segoe UI',Arial,sans-serif;color:#1a1a2e;margin:0;padding:40px;font-size:12px;background:#fff}
.logo-header{display:flex;align-items:center;gap:16px;margin-bottom:24px;border-bottom:3px solid #8DB4B4;padding-bottom:16px}
.logo-header img{height:60px;width:60px;border-radius:50%;object-fit:cover}
.logo-header h1{margin:0;font-size:24px;color:#1a1a2e;letter-spacing:1px}
.quote-badge{display:inline-block;background:#92D050;color:#1a1a2e;padding:4px 12px;border-radius:4px;font-weight:700;font-size:14px;margin-bottom:20px}
.meta-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px 24px;margin-bottom:24px;font-size:12px}
.meta-grid .label{font-weight:600;color:#555}
.meta-grid .value{color:#1a1a2e}
.price-box{background:#f0f7f0;border:2px solid #92D050;border-radius:8px;padding:20px;text-align:center;margin:24px 0}
.price-box .amount{font-size:32px;font-weight:800;color:#1a1a2e}
.price-box .label{font-size:11px;color:#666;text-transform:uppercase;letter-spacing:1px}
.section{margin-top:24px}
.section h3{font-size:14px;font-weight:700;color:#1a1a2e;border-bottom:1px solid #ccc;padding-bottom:4px;margin:0 0 8px}
.section p{margin:4px 0;line-height:1.6;white-space:pre-wrap}
.footer{margin-top:40px;padding-top:12px;border-top:1px solid #ccc;font-size:9px;color:#999;text-align:center}
</style></head><body>
<div class="logo-header">
  ${logoDataUri ? `<img src="${logoDataUri}" alt="Logo"/>` : ""}
  <div><h1>Quotation</h1><p style="margin:0;font-size:11px;color:#666">Rebar Estimation Services</p></div>
</div>
<div class="quote-badge">Quote v${quote.version_number} — ${quote.status?.toUpperCase() || "DRAFT"}</div>
<div class="meta-grid">
  <div><span class="label">Project:</span></div><div class="value">${projectName}</div>
  ${clientName ? `<div><span class="label">Customer:</span></div><div class="value">${clientName}</div>` : ""}
  ${address ? `<div><span class="label">Address:</span></div><div class="value">${address}</div>` : ""}
  <div><span class="label">Date:</span></div><div class="value">${dateStr}</div>
  ${estimateSummary ? `<div><span class="label">Based on Estimate:</span></div><div class="value">v${estimateSummary.version_number} (${fmtPrice(estimateSummary.total_estimated_cost)} est. cost)</div>` : ""}
</div>
<div class="price-box">
  <div class="label">Quoted Price</div>
  <div class="amount">${fmtPrice(quote.quoted_price)}</div>
  <div class="label">${currency}</div>
</div>
${quote.terms_text ? `<div class="section"><h3>Terms & Conditions</h3><p>${quote.terms_text}</p></div>` : ""}
${quote.exclusions_text ? `<div class="section"><h3>Exclusions</h3><p>${quote.exclusions_text}</p></div>` : ""}
<div class="footer">Generated by Rebar Estimator Pro &bull; ${new Date().toISOString()}</div>
</body></html>`;

  const printWindow = window.open("", "_blank");
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.onload = () => setTimeout(() => printWindow.print(), 400);
  } else {
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `Quote_v${quote.version_number}_${projectName.replace(/\s+/g, "_")}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }
}
